spring:
  application:
    name: hello-world-test

server:
  port: 8081  # 테스트용 포트

logging:
  level:
    root: INFO
    com.example.helloworld: DEBUG
  file:
    name: logs/hello-world-test.log

# 테스트 환경 특화 설정
app:
  environment: test
  version: 0.0.1-SNAPSHOT
  debug: true 