server:
  port: 8080

spring:
  application:
    name: hello-world-prod

logging:
  level:
    root: INFO
    com.example.helloworld: INFO
  file:
    name: logs/hello-world-prod.log

# 운영 환경 특화 설정
app:
  environment: production
  version: 1.0.0
  debug: false 