name: Java Build and Test

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B clean package --file pom.xml
    
    - name: Run Tests
      run: mvn -B test --file pom.xml
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifacts
        path: |
          target/*.jar
          target/surefire-reports/
    
    - name: Deploy to Development
      if: github.ref == 'refs/heads/develop'
      run: |
        chmod +x deploy.sh
        ./deploy.sh dev
    
    - name: Deploy to Production
      if: github.ref == 'refs/heads/main'
      run: |
        chmod +x deploy.sh
        ./deploy.sh prod 